export const SET_USER = 'SET_USER';
export const ADD_FAVORITE = 'ADD_FAVORITE';
export const DELETE_FAVORITE = 'DELETE_FAVORITE';
export const RATING_FAVORITE = 'RATING_FAVORITE';
export const COMPLETE_FAVORITE = 'COMPLETE_FAVORITE'
